<?php
require 'vendor/autoload.php';

function export_menu() {

	$items['export'] = array(
		'title' => 'export descriptions',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('export_basic'),
		'access callback' => TRUE,
	);
	return $items;
}

function export_basic($form, &$form_state){
	
	$form = array();

	$form['datamodel1'] = array (
					'#title' => t('Export'),
					'#type' => 'submit',
					'#value' => 'Export Public Service Descriptions',					
				);
			
	return $form;	
	}
	
function export_basic_submit($form, &$form_state) {
	
	if(easyRdf()) {
		
		//Change this variable to point to the correct sparql endpoint
		$endpoint= 'SparqlEndpoint';
		$gs= new EasyRdf_Sparql_client($endpoint);

		//Change in the WHERE clausule the *GRAPHURI* to the correct Graph URI that you have chosen
		$data = $gs->query(
		'CONSTRUCT {?s ?o ?p}		
 			WHERE { GRAPH <*GRAPHURI*> {?s ?o ?p}} 			
 		');
	
 		$dir = getcwd();
		$serialized= $data->serialise('rdfxml');
		$array= $data->resources();
		//Change this variable to export to another directory
 	 	$exportfile= $dir."/sites/export.rdf";
 	 	$fh = fopen($exportfile, "w");
 	 	fwrite($fh, $serialized);
 	 	fclose($fh);
 	}
}


		  